export const CARD_OPTIONS = [
  "Schoppen Aas",
  "Schoppen Heer",
  "Schoppen Dame",
  "Schoppen Boer",
  "Schoppen 10",
  "Harten Aas",
  "Harten Heer",
  "Harten Dame",
  "Harten Boer",
  "Harten 10",
  "Ruiten Aas",
  "Ruiten Heer",
  "Ruiten Dame",
  "Ruiten Boer",
  "Ruiten 10",
  "Klaveren Aas",
  "Klaveren Heer",
  "Klaveren Dame",
  "Klaveren Boer",
  "Klaveren 10",
];