export const DECK52 = [
  // ♠ Schoppen
  { code: "AS", label: "A♠", name: "Schoppen Aas" },
  { code: "KS", label: "K♠", name: "Schoppen Koning" },
  { code: "QS", label: "Q♠", name: "Schoppen Vrouw" },
  { code: "JS", label: "J♠", name: "Schoppen Boer" },
  { code: "10S", label: "10♠", name: "Schoppen 10" },
  { code: "9S", label: "9♠", name: "Schoppen 9" },
  { code: "8S", label: "8♠", name: "Schoppen 8" },
  { code: "7S", label: "7♠", name: "Schoppen 7" },
  { code: "6S", label: "6♠", name: "Schoppen 6" },
  { code: "5S", label: "5♠", name: "Schoppen 5" },
  { code: "4S", label: "4♠", name: "Schoppen 4" },
  { code: "3S", label: "3♠", name: "Schoppen 3" },
  { code: "2S", label: "2♠", name: "Schoppen 2" },

  // ♥ Harten
  { code: "AH", label: "A♥", name: "Harten Aas" },
  { code: "KH", label: "K♥", name: "Harten Koning" },
  { code: "QH", label: "Q♥", name: "Harten Vrouw" },
  { code: "JH", label: "J♥", name: "Harten Boer" },
  { code: "10H", label: "10♥", name: "Harten 10" },
  { code: "9H", label: "9♥", name: "Harten 9" },
  { code: "8H", label: "8♥", name: "Harten 8" },
  { code: "7H", label: "7♥", name: "Harten 7" },
  { code: "6H", label: "6♥", name: "Harten 6" },
  { code: "5H", label: "5♥", name: "Harten 5" },
  { code: "4H", label: "4♥", name: "Harten 4" },
  { code: "3H", label: "3♥", name: "Harten 3" },
  { code: "2H", label: "2♥", name: "Harten 2" },

  // ♦ Koeken
  { code: "AD", label: "A♦", name: "Koeken Aas" },
  { code: "KD", label: "K♦", name: "Koeken Koning" },
  { code: "QD", label: "Q♦", name: "Koeken Vrouw" },
  { code: "JD", label: "J♦", name: "Koeken Boer" },
  { code: "10D", label: "10♦", name: "Koeken 10" },
  { code: "9D", label: "9♦", name: "Koeken 9" },
  { code: "8D", label: "8♦", name: "Koeken 8" },
  { code: "7D", label: "7♦", name: "Koeken 7" },
  { code: "6D", label: "6♦", name: "Koeken 6" },
  { code: "5D", label: "5♦", name: "Koeken 5" },
  { code: "4D", label: "4♦", name: "Koeken 4" },
  { code: "3D", label: "3♦", name: "Koeken 3" },
  { code: "2D", label: "2♦", name: "Koeken 2" },

  // ♣ Klaver
  { code: "AC", label: "A♣", name: "Klaver Aas" },
  { code: "KC", label: "K♣", name: "Klaver Koning" },
  { code: "QC", label: "Q♣", name: "Klaver Vrouw" },
  { code: "JC", label: "J♣", name: "Klaver Boer" },
  { code: "10C", label: "10♣", name: "Klaver 10" },
  { code: "9C", label: "9♣", name: "Klaver 9" },
  { code: "8C", label: "8♣", name: "Klaver 8" },
  { code: "7C", label: "7♣", name: "Klaver 7" },
  { code: "6C", label: "6♣", name: "Klaver 6" },
  { code: "5C", label: "5♣", name: "Klaver 5" },
  { code: "4C", label: "4♣", name: "Klaver 4" },
  { code: "3C", label: "3♣", name: "Klaver 3" },
  { code: "2C", label: "2♣", name: "Klaver 2" },
];

export const CARD_BY_CODE = Object.fromEntries(DECK52.map((c) => [c.code, c]));