export const KLEURENWIEZEN_CONTRACTS = [
  {
    id: "SAMEN_8",
    label: "Samen 8",
    desc: "Emballage / vragen & meegaan. Twee tegen twee, minstens 8 slagen.",
    needsTrump: true,
    needsPartner: true,
    targetType: "atLeast",
    targetTricks: 8,
    teamMode: "pair",
    successScores: [7, 10, 13, 16, 19, 30],
    failStart: 10,
    failStep: 3,
    failMax: 30,
    failOppBase: 10,
    failOppStep: 3,
    failOppMax: 30,
    order: 1,
  },
  {
    id: "SAMEN_9",
    label: "Samen 9",
    desc: "Emballage / vragen & meegaan. Twee tegen twee, minstens 9 slagen.",
    needsTrump: true,
    needsPartner: true,
    targetType: "atLeast",
    targetTricks: 9,
    teamMode: "pair",
    successScores: [10, 13, 16, 19, 30],
    failStart: 13,
    failStep: 3,
    failMax: 30,
    failOppBase: 13,
    failOppStep: 3,
    failOppMax: 30,
    order: 2,
  },
  {
    id: "SOLO_6",
    label: "Solo 6",
    desc: "Solo tegen drie. Declarant moet minstens 6 slagen halen.",
    needsTrump: true,
    needsPartner: false,
    targetType: "atLeast",
    targetTricks: 6,
    teamMode: "solo",
    successScores: [12, 15, 18],
    failStart: 15,
    failStep: 3,
    failMax: 30,
    failOppBase: 10,
    failOppStep: 2,
    failOppMax: 20,
    order: 3,
  },
  {
    id: "SAMEN_10",
    label: "Samen 10",
    desc: "Emballage / vragen & meegaan. Twee tegen twee, minstens 10 slagen.",
    needsTrump: true,
    needsPartner: true,
    targetType: "atLeast",
    targetTricks: 10,
    teamMode: "pair",
    successScores: [13, 16, 19, 30],
    failStart: 16,
    failStep: 3,
    failMax: 30,
    failOppBase: 16,
    failOppStep: 3,
    failOppMax: 30,
    order: 4,
  },
  {
    id: "SOLO_7",
    label: "Solo 7",
    desc: "Solo tegen drie. Declarant moet minstens 7 slagen halen.",
    needsTrump: true,
    needsPartner: false,
    targetType: "atLeast",
    targetTricks: 7,
    teamMode: "solo",
    successScores: [15, 18],
    failStart: 18,
    failStep: 3,
    failMax: 30,
    failOppBase: 12,
    failOppStep: 2,
    failOppMax: 20,
    order: 5,
  },
  {
    id: "SAMEN_11",
    label: "Samen 11",
    desc: "Emballage / vragen & meegaan. Twee tegen twee, minstens 11 slagen.",
    needsTrump: true,
    needsPartner: true,
    targetType: "atLeast",
    targetTricks: 11,
    teamMode: "pair",
    successScores: [16, 19, 30],
    failStart: 19,
    failStep: 3,
    failMax: 30,
    failOppBase: 19,
    failOppStep: 3,
    failOppMax: 30,
    order: 6,
  },
  {
    id: "KLEINE_MISERIE",
    label: "Kleine miserie",
    desc: "Declarant probeert geen enkele slag te halen. Er worden 12 slagen gespeeld.",
    needsTrump: false,
    needsPartner: false,
    targetType: "exact",
    targetTricks: 0,
    totalTricks: 12,
    instantFailOnDeclarantTrick: true,
    allowEarlyClaim: false,
    teamMode: "solo",
    successPoints: 18,
    failPlayersPoints: -18,
    failOppPoints: 12,
    order: 7,
  },
  {
    id: "SOLO_8",
    label: "Solo 8",
    desc: "Solo tegen drie. Declarant moet minstens 8 slagen halen.",
    needsTrump: true,
    needsPartner: false,
    targetType: "atLeast",
    targetTricks: 8,
    teamMode: "solo",
    successPoints: 21,
    failStart: 24,
    failStep: 3,
    failMax: 30,
    failOppBase: 16,
    failOppStep: 2,
    failOppMax: 20,
    order: 8,
  },
  {
    id: "SAMEN_12",
    label: "Samen 12",
    desc: "Emballage / vragen & meegaan. Twee tegen twee, minstens 12 slagen.",
    needsTrump: true,
    needsPartner: true,
    targetType: "atLeast",
    targetTricks: 12,
    teamMode: "pair",
    successScores: [22, 30],
    failStart: 25,
    failStep: 3,
    failMax: 31,
    failOppBase: 25,
    failOppStep: 3,
    failOppMax: 31,
    order: 9,
  },
  {
    id: "PICCOLO",
    label: "Piccolo",
    desc: "Declarant moet exact 1 slag halen.",
    needsTrump: false,
    needsPartner: false,
    targetType: "exact",
    targetTricks: 1,
    teamMode: "solo",
    successPoints: 27,
    failPlayersPoints: -27,
    failOppPoints: 18,
    order: 10,
  },
  {
    id: "SAMEN_13",
    label: "Samen 13",
    desc: "Emballage / vragen & meegaan. Twee tegen twee, alle 13 slagen.",
    needsTrump: true,
    needsPartner: true,
    targetType: "exact",
    targetTricks: 13,
    teamMode: "pair",
    successPoints: 30,
    failStart: 33,
    failStep: 3,
    failMax: 39,
    failOppBase: 33,
    failOppStep: 3,
    failOppMax: 39,
    order: 11,
  },
  {
    id: "TROEL",
    label: "Troel",
    desc: "Partner handmatig kiezen. Eigen troef = 8 slagen, andere troef = 9 slagen.",
    needsTrump: true,
    needsPartner: true,
    needsTroelMode: true,
    targetType: "atLeast",
    targetTricks: 8,
    teamMode: "pair",
    troelSuccessOwn: 15,
    troelSuccessOther: 30,
    failPlayersPoints: 0,
    failOppPoints: 15,
    order: 12,
  },
  {
    id: "ABONDANCE_9",
    label: "Abondance 9",
    desc: "Declarant moet minstens 9 slagen halen.",
    needsTrump: true,
    needsPartner: false,
    targetType: "atLeast",
    targetTricks: 9,
    teamMode: "solo",
    successPoints: 30,
    failPlayersPoints: -30,
    failOppPoints: 20,
    order: 13,
  },
  {
    id: "GROTE_MISERIE",
    label: "Grote miserie",
    desc: "Declarant probeert geen enkele slag te halen. Hogere contractwaarde.",
    needsTrump: false,
    needsPartner: false,
    targetType: "exact",
    targetTricks: 0,
    totalTricks: 13,
    instantFailOnDeclarantTrick: true,
    allowEarlyClaim: false,
    teamMode: "solo",
    successPoints: 36,
    failPlayersPoints: -36,
    failOppPoints: 24,
    order: 14,
  },
  {
    id: "ABONDANCE_10",
    label: "Abondance 10",
    desc: "Declarant moet minstens 10 slagen halen.",
    needsTrump: true,
    needsPartner: false,
    targetType: "atLeast",
    targetTricks: 10,
    teamMode: "solo",
    successPoints: 45,
    failPlayersPoints: -45,
    failOppPoints: 30,
    order: 15,
  },
  {
    id: "ABONDANCE_11",
    label: "Abondance 11",
    desc: "Declarant moet minstens 11 slagen halen.",
    needsTrump: true,
    needsPartner: false,
    targetType: "atLeast",
    targetTricks: 11,
    teamMode: "solo",
    successPoints: 60,
    failPlayersPoints: -60,
    failOppPoints: 40,
    order: 16,
  },
  {
    id: "MISERIE_OP_TAFEL",
    label: "Miserie op tafel",
    desc: "Open miserie / blote miserie op tafel.",
    needsTrump: false,
    needsPartner: false,
    targetType: "exact",
    targetTricks: 0,
    totalTricks: 13,
    instantFailOnDeclarantTrick: true,
    allowEarlyClaim: false,
    teamMode: "solo",
    successPoints: 72,
    failPlayersPoints: -72,
    failOppPoints: 48,
    order: 17,
  },
  {
    id: "KLEINE_SOLOSLIM",
    label: "Kleine soloslim",
    desc: "Declarant moet alle 13 slagen halen.",
    needsTrump: true,
    needsPartner: false,
    targetType: "exact",
    targetTricks: 13,
    teamMode: "solo",
    successPoints: 100,
    failPlayersPoints: -100,
    failOppPoints: 66,
    order: 18,
  },
  {
    id: "GROTE_SOLOSLIM",
    label: "Grote soloslim",
    desc: "Grote chelem. Declarant moet alle 13 slagen halen.",
    needsTrump: true,
    needsPartner: false,
    targetType: "exact",
    targetTricks: 13,
    teamMode: "solo",
    successPoints: 150,
    failPlayersPoints: -150,
    failOppPoints: 100,
    order: 19,
  },
].sort((a, b) => a.order - b.order);

export const CONTRACT_BY_ID = Object.fromEntries(
  KLEURENWIEZEN_CONTRACTS.map((contract) => [contract.id, contract])
);

export function getKleurenwiezenContract(contractId) {
  return CONTRACT_BY_ID[contractId] ?? null;
}
